Abdominal disorder
Arthritis
Asthma
BackacheBackache
BronchitisBronch
coldcold
ConstipationCons
DepressionDepres
DiabetiesDiabeti
EyestrainEyestra
Gall Bladder Disor
HeadacheHeadache
IndigestionIndig
InsomniaInsomnia
Kedney DisorderK
Liver DisorderLi
Menopouse Disorder
NeurostheniaNeur
ObesityObesity
PilesPiles
Poor PosturePoor
ProstateProstate
ReproductiveRepr
RheumatismRheuma
SciaticaSciatica
Sexual Disability
SinusSinus
Skin DiseaseSkin
Throat Discorder
Thyroid Discorder
Varicose 
Wind Pain 
Wrenkles